name: Node CI

on: 
  push:
    branches: 'main'
    paths: '**.js'
  pull_request:
    branches: 'main'

env:
  CI: true
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install
      - run: make lint
      - uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: make test-coverage
          debug: true
      - run: snyk test
      - run: snyk code test
